<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\User;

class DealsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('deals')->insert([
            [
                'user_id' => User::where('email', 'mdelacruz@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0001',
                'deal_name' => 'Zeta Prime Properties',
                'industry' => 'Developer',
                'product_type' => 'White-Label',
                'property_owner_tag' => 'Developer',
                'contact_name' => 'Cybille Renomeron',
                'designation' => 'Operations Manager',
                'contact_number' => '0977 417 4985',
                'email_address' => null,
                'deal_size' => null,
                'potential_income' => 1000000.00,
                'deal_stage' => 'Lead',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'Low',
                'from_date' => Carbon::createFromDate(2022, 1, 1),
                'expected_close_date' => Carbon::createFromDate(2024, 10, 1),
                'next_step' => 'Last part of training, Onboarding',
                'remarks' => 'Waiting for LTS. Onboarding and Admin Training',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => User::where('email', 'johna@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0002',
                'deal_name' => 'Gen Realty',
                'industry' => 'Brokerage',
                'product_type' => 'SaaS',
                'property_owner_tag' => 'Broker',
                'contact_name' => 'Arriane Pabale',
                'designation' => 'Broker',
                'contact_number' => null,
                'email_address' => null,
                'deal_size' => null,
                'potential_income' => null,
                'deal_stage' => 'Appointment',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'High',
                'from_date' => Carbon::createFromDate(2024, 11, 8),
                'expected_close_date' => Carbon::createFromDate(2024, 12, 20),
                'next_step' => 'For follow up',
                'remarks' => 'Enlistment of multiple properties',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => User::where('email', 'mdelacruz@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0003',
                'deal_name' => 'M.A. Magtibay Real Estate',
                'industry' => 'Brokerage',
                'product_type' => 'SaaS',
                'property_owner_tag' => 'Broker',
                'contact_name' => 'Mario Magtibay',
                'designation' => 'Owner',
                'contact_number' => '0917 144 8269 / 0917 712 7000',
                'email_address' => null,
                'deal_size' => '100 agents',
                'potential_income' => 270000.00,
                'deal_stage' => 'Appointment',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'High',
                'from_date' => Carbon::createFromDate(2024, 1, 9),
                'expected_close_date' => Carbon::createFromDate(2024, 1, 30),
                'next_step' => '12/17/24 Migs- Will have a meeting first week of January.',
                'remarks' => 'They focus on Hana Sofie brand which is not a real estate product',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => User::where('email', 'mdelacruz@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0004',
                'deal_name' => 'Karen Ganzon',
                'industry' => 'Brokerage',
                'product_type' => 'SaaS',
                'property_owner_tag' => 'Broker',
                'contact_name' => 'Karen Ganzon',
                'designation' => 'Broker',
                'contact_number' => '0917 785 4378',
                'email_address' => null,
                'deal_size' => null,
                'potential_income' => null,
                'deal_stage' => 'Lead',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'High',
                'from_date' => null,
                'expected_close_date' => null,
                'next_step' => 'For follow up',
                'remarks' => 'She will refer potential opportunities',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => User::where('email', 'mdelacruz@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0005',
                'deal_name' => 'Crown Asia Sales and Marketing',
                'industry' => 'Developer',
                'product_type' => 'SaaS',
                'property_owner_tag' => 'Developer',
                'contact_name' => 'Joel Bayan',
                'designation' => 'Director',
                'contact_number' => null,
                'email_address' => null,
                'deal_size' => '40 agents',
                'potential_income' => 108000.00,
                'deal_stage' => 'Closed Lost',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'High',
                'from_date' => Carbon::createFromDate(2024, 11, 8),
                'expected_close_date' => Carbon::createFromDate(2024, 12, 20),
                'next_step' => 'Waiting for their SVP for a meeting',
                'remarks' => '10 sign ups (not paid)',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => User::where('email', 'mdelacruz@realhomes.ph')->first()?->id,
                'deal_number' => 'DN-0006',
                'deal_name' => 'FNG Group',
                'industry' => 'Developer',
                'product_type' => 'SaaS',
                'property_owner_tag' => 'Developer',
                'contact_name' => 'Joshua Generoso',
                'designation' => 'Sales Head',
                'contact_number' => null,
                'email_address' => 'joshuageneroso429@gmail.com',
                'deal_size' => '40 agents',
                'potential_income' => 108000.00,
                'deal_stage' => 'Appointment',
                'probability' => null,
                'weighted_forecast' => null,
                'priority' => 'High',
                'from_date' => Carbon::createFromDate(2024, 11, 8),
                'expected_close_date' => Carbon::createFromDate(2024, 12, 20),
                'next_step' => null,
                'remarks' => 'After Christmas party, due to busy manning sched',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Continue adding more deals here as required
        ]);
    }
}
